# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_auto_20180822_0757'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingticket',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buses.Trip'),
            preserve_default=False,
        ),
    ]
