# Generated by Django 2.1 on 2018-08-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_trackingticket_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketalertrecepients',
            name='ticket',
            field=models.ForeignKey(on_delete=None, to='clients.TrackingTicket'),
        ),
        migrations.AlterField(
            model_name='trackingticket',
            name='client',
            field=models.ForeignKey(on_delete=None, to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='trackingticket',
            name='trip',
            field=models.ForeignKey(on_delete=None, to='buses.Trip'),
        ),
    ]
