# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-22 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buses.BusCompany'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='routes',
            field=models.ManyToManyField(to='buses.Route'),
        ),
        migrations.AddField(
            model_name='route',
            name='checkpoints',
            field=models.ManyToManyField(blank=True, null=True, related_name='checkpoints', to='buses.RouteCheckPoint'),
        ),
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='buses.RouteCheckPoint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='starting_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='point_of_origin', to='buses.RouteCheckPoint'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='bus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buses.Bus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buses.Route'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buses.BusSchedule'),
            preserve_default=False,
        ),
    ]
