# Generated by Django 2.1 on 2018-08-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_auto_20180822_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='company',
            field=models.ForeignKey(on_delete=None, to='buses.BusCompany'),
        ),
        migrations.AlterField(
            model_name='buscompany',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\nakamura9a\\Documents\\code\\git\\bus_tracker\\media'),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(on_delete=None, related_name='destination', to='buses.RouteCheckPoint'),
        ),
        migrations.AlterField(
            model_name='route',
            name='starting_point',
            field=models.ForeignKey(on_delete=None, related_name='point_of_origin', to='buses.RouteCheckPoint'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='bus',
            field=models.ForeignKey(on_delete=None, to='buses.Bus'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(on_delete=None, to='buses.Route'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='schedule',
            field=models.ForeignKey(on_delete=None, to='buses.BusSchedule'),
        ),
    ]
